import type { Metadata } from 'next';
import NavTabList from '@/components/NavTabList/NavTabList';
import navData from '@/data/nav-data';
import './globals.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <div className="container">
          <aside className="container__sidebar">
            <NavTabList
              navTabs={navData.map(item => item.tab)}
              className="container__nav-tab-list"
            />
          </aside>
          <main className="container__main">{children}</main>
        </div>
      </body>
    </html>
  );
}
